### ISSUE TITLE
derive(FromRepr) broken in 0.25.0

### ISSUE THREAD

**Issue by uklotzde** [Peternator7/strum#275]
![image](https://github.com/Peternator7/strum/assets/1474154/ca82a8f8-dc4c-40d1-9c74-8aca4205b825)

Worked flawlessly with 0.24.1

**Comment by uklotzde** [comment]
I suggest to yank v0.25.0 until the issues with doc comments are resolved.

**Comment by uklotzde** [comment]
> Please do not yank!

Agreed. I didn't consider that the derive macros are a separate feature.

**Comment by Peternator7** [comment]
Like Martin said, we can't really rollback, 0.25 already had 10,000 downloads so people have already updated, and this would break them.

Pinning to `0.24` is definitely the correct solution for affected users until a patch fix is released.

**Comment by Peternator7** [comment]
Fixed in 0.25.1. Thanks @smoelius

**Comment by uklotzde** [comment]
Please consider releasing the bugfix soon. Versions are cheap and not a scarce resource.

**Comment by Peternator7** [comment]
I released it yesterday. You might need to run `cargo update` to pick up the patch version if you pinned to `0.25.`

**Comment by uklotzde** [comment]
Still 0.25.0 on crates.io at this moment.

**Comment by uklotzde** [comment]
The corresponding Git tags are also missing. I suggest to tag each release to ensure traceability.

**Comment by uklotzde** [comment]
The main crate is still at 0.25.0 and pulls strum_macros 0.25.0. That doesn't fix the issue.

**Comment by jessebraham** [comment]
The issue is resolved, even though `strum` lists the required version of `strum_macros` as `0.25.0` it will still pull in any subsequent patch releases, as this is all semver compatible.

If you're still having build issues you need to try to clean and update first. I was experiencing this `FromRepr` issue in a few projects and simply running `cargo update` prior to re-building has fixed it in all of them.

**Comment by Peternator7** [comment]
There's 2 packages, strum and strum_macros; since this bug only affected codegen, only [strum_macros](https://crates.io/crates/strum_macros/0.25.1) needed a new version

**Comment by uklotzde** [comment]
Thanks for the clarification. It is confusing that it suddenly works even though the main crate is still at 0.25.0. Beforehand I always needed to downgrade it manually from 0.25.0 to 0.24.1 after running `cargo upgrade --incompatible`. If the `Cargo.lock` file is not part of the repo you don't notice this change behind the scenes.
